Repository glpi-project/php-library-glpi, pull requests merged in 2018-03, with the labels that each got.

#54 Install dev requirement for test
  .travis.yml
Labels: ci

#56 Update release script code
  .github/publish_changes.sh
Labels: ci

#58 CI shell change
  .github/publish_changes.sh
Labels: ci

#57 Fix path for documentation
  _includes/header.html
Labels: documentation

#59 Robo build update
  RoboFile.php
Labels: build

#60 Patch for robo script task
  RoboFile.php
Labels: build

#62 Robo script update for changelog
  RoboFile.php
Labels: build
